### PR TITLE
Extract engines and decorators

### LINKED ISSUE #88: Splitting the decorators from the core
Right now, when using this package without immutable, it will still require immutablejs which is quite big.

Each decorators should be required separately or be in its own package.

### PR DESCRIPTION
**Pull request by michaelcontento**
Closes #88

### CODE REVIEW

**Comment by michaelcontento** [comment]
@mathieudutour @alizbazar What do you think about this change?

@mathieudutour I haven't converted the migrate decorator, as it's you contribution and I don't want to claim all the fame for this cool decorator! So go ahead and create a `redux-storage-decorator-migrate` npm package :sunglasses:

**Comment by mathieudutour** [comment]
there it is: https://github.com/mathieudutour/redux-storage-decorator-migrate

**Comment by michaelcontento** [comment]
@mathieudutour: Whoop! Whoop! Nice and thank you very much :tada: 

I'll let this PR sit for one night and revisit it tomorrow. If everything is fine, the v3.0.0 will be released :shipit:

**Comment by mathieudutour** [comment]
:+1:

**Pull request merged**
