### PR TITLE
remove immutableJS from dependencies

### LINKED ISSUE #93: Optional require of Immutable is broken
It's impossible to build without `immutable`, browserify is throwing a compile time error. Maybe using https://github.com/devongovett/browserify-optional would work but it still need 
```
"browserify": {
  "transform": ["browserify-optional"]
}
```
in the package.json. 

Another solution would be to pass `fromJS` as an optional argument of the reducer enhancer.

### PR DESCRIPTION
**Pull request by mathieudutour**
fix #93

### CODE REVIEW

**Comment by michaelcontento** [comment]
What if the user does not pass in `fromJS` but the state contains some immutable objects? Currently this would fail, as we're calling a undefined function. 

Better would be to throw hard with a good/helpful message. Or do you know a good fallback strategy?

**Comment by michaelcontento** [comment]
Another idea would be to remove the whole `fromJS` stuff from `redux-storage` and allow a custom merger function to be passed. 

So you want to use `redux-storage` with ImmutableJS? Use this:
```js
import merger from 'redux-storage-merger-immutablejs';
const reducer = storage.reducer(combineReducers(reducers), merger);
```

You don't use ImmutableJS at all? There is nothing to change, as the `merger` option is optional :sunglasses:

**Comment by mathieudutour** [comment]
Yeah good idea :+1:

**Comment by michaelcontento** [comment]
Sorry for the slow progress :disappointed: But I'll do my best to find some spare time next week!

**Comment by michaelcontento** [comment]
Closed - please have a look at #104

**Pull request closed without merging**
