### PR TITLE
Use modular versions of lodash functions

### PR DESCRIPTION
**Pull request by dbachrach**

### CODE REVIEW

**Comment by dbachrach** [comment]
@michaelcontento Can we get a new official release when you have a chance? Thanks!

**Comment by michaelcontento** [comment]
Sure, `1.2.4` published to npm :beers:

**Comment by dbachrach** [comment]
:+1: Thanks

**Comment by romulof** [comment]
At first I thought it was a good idea, but after my project got bigger I realized that most of my 3rd party packages uses monolithic version of Lodash, so I ended up with 2 versions of the same function. For example: `lodash.merge` and `lodash/merge`.

Webpack 1 only produces big bundles if importing from Lodash root module (`import { merge } from 'lodash'`), but importing an specific module (`import merge from 'lodash/merge'`) have the same result as importing the modular version (`import merge from 'lodash.merge'`).

I'd recommend reverting to monolithic version of Lodash to keep in sync with most of other packages.

**Comment by romulof** [comment]
Quick explanation of how import works on Webpack 1:

`import { merge } from 'lodash'` imports everything declared by Lodash index file (an object containing all the functions) then apply destructure to get `merge` function. The bundle increases a lot because all unused functions are still declared in the imported object.
`import merge from 'lodash/merge'` imports the only the `merge` function.

This applies to almost all 3rd packages, including redux:
```es6
import createStore from 'redux/lib/createStore';
import applyMiddleware from 'redux/lib/applyMiddleware';
import compose from 'redux/lib/compose';
...
```

On Webpack 2 there will be an tree-shaking optimization allowing ES6 modules imported using destructure notation to be shrieked. More here: http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Pull request merged**
