### PR TITLE
Add meta.origin to our saveAction if NODE_ENV != production

### LINKED ISSUE #100: Tracking down instigators of SAVE
Love this package! :)

I'm using redux-storage-decorator-filter to restrict the save calls to a specific part of the state. I also just started using redux-sagas, so I put the three `EFFECT_*` actions into the storage blacklist, and they both work together beautifully.
However, I'm getting an extra `REDUX_STORAGE_SAVE` action which I have no clue why it's being dispatched, and there is no information I can see to help me figure it out. How do I track down the part of the code that caused the save operation to happen ... ?

Thanks !
-Guy

### PR DESCRIPTION
**Pull request by michaelcontento**
Fixes #100

### CODE REVIEW

**Comment by michaelcontento** [comment]
@mathieudutour Do you have a opinion about this? You're quite active on this project and I'd love to hear  your feedback :smile:

**Comment by mathieudutour** [comment]
Yeah it might be useful. This is a breaking change though. And you need to add 
```
"browserify": {
    "transform": [
      "envify"
    ]
  },
```
to the package.json

**Comment by michaelcontento** [comment]
@mathieudutour I've added envify (the faster variant named [loose-envify](https://github.com/zertosh/loose-envify) - the same as [redux](https://github.com/reactjs/redux/blob/master/package.json#L116-L120) is using).

But why should this be a breaking change? It does not manipulate the actual payload of the save action. I though of this as a minor release

**Comment by mathieudutour** [comment]
Because of someone is already using the origin meta, it breaks.

For it to be non-breaking, it needs to be opt-in

On 29 Feb 2016, at 08:51, Michael Contento <notifications@github.com> wrote:

@mathieudutour <https://github.com/mathieudutour> I've added envify (the
faster variant named loose-envify <https://github.com/zertosh/loose-envify>
- the same as redux
<https://github.com/reactjs/redux/blob/master/package.json#L116-L120> is
using).

But why should this be a breaking change? It does not manipulate the actual
payload of the save action. I though of this as a minor release

—
Reply to this email directly or view it on GitHub
<https://github.com/michaelcontento/redux-storage/pull/102#issuecomment-190107501>
.

**Comment by michaelcontento** [comment]
Oh! You mean if someone hijacks and mutates the saveAction while it is been processed? Good point! Although this sounds more like a redux anti-pattern to me :smile: 

But as this is a good point, it will be part of the upcoming 4.0.0 together with the `fromJS` changes :+1:

**Comment by michaelcontento** [comment]
**NOTE**: Branch rebased as `browserify-envify` is already required in the current master

**Comment by mathieudutour** [comment]
No not necessary. I have some middlewares checking for the existence of a
meta key to trigger a side effect. Someone could have one of those
listening to the origin meta key

On 29 Feb 2016, at 09:16, Michael Contento <notifications@github.com> wrote:

Oh! You mean if someone hijacks and mutates the saveAction while it is been
processed? Good point! Although this sounds more like a redux anti-pattern
to me [image: :smile:]

But as this is a good point, it will be part of the upcoming 4.0.0 together
with the fromJS changes [image: :+1:]

—
Reply to this email directly or view it on GitHub
<https://github.com/michaelcontento/redux-storage/pull/102#issuecomment-190115959>
.

**Pull request merged**
